In [167]:
import functools
import numpy as np
import math

In [127]:
#day1
with open('advent2021/day1.txt') as f:
    lines = f.readlines()

lines = list(map(int, lines))
num1 = lines[0]
increased_count = 0
decreased_count = 0
flat_count = 0

for n in range(1, len(lines)):
    num2 = lines[n]
    if num2==num1:
        flat_count += 1
    elif num2>num1:
        increased_count +=1
    else:
        decreased_count +=1
    num1 = num2
        
print(f"{flat_count=}")
print(f"{increased_count=}")
print(f"{decreased_count=}")
        
    

flat_count=0
increased_count=1713
decreased_count=286


In [130]:
lines2 = [lines[i] + lines[i+1] + lines[i+2] for i in range(len(lines) - 2)]

num1 = lines2[0]
increased_count = 0
decreased_count = 0
flat_count = 0

for n in range(1, len(lines2)):
    num2 = lines2[n]
    if num2==num1:
        flat_count += 1
    elif num2>num1:
        increased_count +=1
    else:
        decreased_count +=1
    num1 = num2
        
print(f"{flat_count=}")
print(f"{increased_count=}")
print(f"{decreased_count=}")

flat_count=40
increased_count=1734
decreased_count=223


In [132]:
#day2

with open('advent2021/day2.txt') as f:
    lines = f.readlines()

In [137]:
# part 1

x = 0
y = 0

for l in lines:
    d, n = l.split(' ')
    n = int(n)
    if d=='forward':
        x+=n
    elif d=='down':
        y+=n
    elif d=='up':
        y-=n
    else:
        print(f'error: {l}')
        
print(f'{x=}, {y=}, {x*y=}')

x=1939, y=1109, x*y=2150351


In [138]:
# part 2

x = 0
y = 0
aim = 0

for l in lines:
    d, n = l.split(' ')
    n = int(n)
    if d=='forward':
        x+=n
        y+=aim*n
    elif d=='down':
        aim+=n
    elif d=='up':
        aim-=n
    else:
        print(f'error: {l}')
        
print(f'{x=}, {y=}, {x*y=}')

x=1939, y=950357, x*y=1842742223


In [199]:
#day3
from scipy.stats import mode

with open('advent2021/day3.txt') as f:
    lines = f.readlines()
    
# parse data
def str_to_numbers(s):
    return [int(c) for c in s]

lines = list(map(lambda l: l[:-1], lines))
data = [str_to_numbers(l) for l in lines]
arr = np.array(data)
arr.shape

(1000, 12)

In [200]:
# part 1

gamma_list = []
for i in range(12):
    gamma_list.append(mode(arr[:, i])[0][0])

epsilon_list = list(map(lambda x:1-x, gamma_list))

gamma = int('0b'+''.join([str(n) for n in gamma_list]), 2)
epsilon = int('0b'+''.join([str(n) for n in epsilon_list]), 2)

print(f'{gamma=}, {epsilon=}, {gamma*epsilon=}')

gamma=3529, epsilon=566, gamma*epsilon=1997414


In [201]:
# part 2 - oxygen 

oxygen_arr = arr.copy()

oxygen_list = []
for i in range(12):
    length = oxygen_arr.shape[0]
    if length==1:
        oxygen_list=list(oxygen_arr[0])
        break

    count = mode(oxygen_arr[:, i])[1][0]
    v = 1 if count == length/2 else mode(oxygen_arr[:, i])[0][0]
    
    oxygen_list.append(v)

    oxygen_arr = oxygen_arr[oxygen_arr[:,i]==v]
    
oxygen = int('0b'+''.join([str(n) for n in oxygen_list]), 2)



In [233]:
# part 2 - co2 

co2_arr = arr.copy()

co2_list = []
for i in range(12):
    length = co2_arr.shape[0]
    if length==1:
        co2_list=list(co2_arr[0])
        break

    count = mode(co2_arr[:, i])[1][0]
    v = 0 if count == length/2 else mode(co2_arr[:, i])[0][0]

    co2_list.append(v)

    co2_arr = co2_arr[co2_arr[:,i]==v]
    
co2 = int('0b'+''.join([str(n) for n in co2_list]), 2)

print(f'{oxygen=}, {co2=}, {oxygen*co2=}')

In [76]:
#day 4

with open('advent2021/day4.txt') as f:
    lines = f.readlines()

# variable setup
boards = []
boards_mask = []
win_mask = [False] * 100
board = []

# parse data
seq_input = [int(n) for n in lines[0].split(',')]

for line in lines[2:]:
    if line=='\n':
        boards.append(np.array(board))
        boards_mask.append(np.zeros((5,5)))
        board = []
    else:
        board.append([int(line[i*3:i*3+2]) for i in range(0,5)])
        
# append the last board record
boards.append(np.array(board))
boards_mask.append(np.zeros((5,5)))

In [89]:
# updating algo - for both parts

win_seq = 0
seq=[]

for n in seq_input:
    for i in range(len(boards)):
        if win_mask[i] == False:        
            boards_mask[i] += (boards[i] == n)

            win = np.any(boards_mask[i].sum(axis=0)==5) or np.any(boards_mask[i].sum(axis=1)==5)
                  
            if win:
                win_mask[i] = True
                seq.append((i, n))


In [92]:
# print results
# part 1 - first win board 
# part 2 - last win board 

first_win_board, first_win_num = seq[0]
last_win_board, last_win_num = seq[-1]

for b in [('first', first_win_board, first_win_num), ('last', last_win_board, last_win_num)]:
    name, idx, win_num = b
    print(f'{name} win board = {idx}')
    print(boards[idx])
    print(boards_mask[idx])

    score = win_num * (boards[idx] * (1 - boards_mask[idx])).sum()
    print(f'{score=}')


first win board = 36
[[80 16 10 79 55]
 [93 60  4  0 29]
 [ 7 97  3  9 86]
 [43 67 78 64 35]
 [44 83 40 33 12]]
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]]
score=51776.0
last win board = 34
[[ 6  3 41  5 44]
 [91 21 32 49 81]
 [29 85 47 20 14]
 [99 31 43 22 69]
 [90  4 45  8 16]]
[[1. 0. 1. 1. 0.]
 [1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]]
score=16830.0


In [93]:
# day 5

with open('advent2021/day5.txt') as f:
    lines = f.readlines()
    
# parse data

import re
p = re.compile('(\d+),(\d+) -> (\d+),(\d+)')

data = [p.match(l).groups() for l in lines]
data = [(int(l[0]), int(l[1]), int(l[2]), int(l[3])) for l in data]

In [169]:
# part 1
space = np.zeros((1000, 1000))

for d in data:
    x0, y0, x1, y1 = d
    if (x0==x1) or (y0==y1):
        space[min(y0,y1):max(y0,y1)+1, min(x0,x1):max(x0,x1)+1] += 1
        
print((space>=2).sum())

6856


In [195]:
#part 2
space = np.zeros((1000, 1000))


for d in data:
    x0, y0, x1, y1 = d
    if (x0==x1) or (y0==y1): #straight line
        space[min(y0,y1):max(y0,y1)+1, min(x0,x1):max(x0,x1)+1] += 1
    elif abs(x0-x1)==abs(y0-y1): #diagonal line
        steps = abs(x0-x1) + 1
        x_direction = int(math.copysign(1, x1-x0))
        y_direction = int(math.copysign(1, y1-y0))
        
        for s in range(steps):
            _y = y0 + s*y_direction
            _x = x0 + s*x_direction
            space[_y, _x] += 1

        
print((space>=2).sum())

20666


In [237]:
# day 6

with open('advent2021/day6.txt') as f:
    lines = f.readlines()
    
fishes = lines[0].strip().split(',')
data = [int(fish) for fish in fishes]

In [238]:
# part 1

total_days = 80

fishes = data.copy()
for day in range(total_days):
    new_fish = []
    for idx, fish in enumerate(fishes):

        if fish==0: 
            new_fish.append(8)
        fishes[idx] = (fish - 1) if fish>0 else 6
    fishes.extend(new_fish)
    
len(fishes)

362666

In [270]:
# part 2 - same question, anther implementation given computation time

fishes = data.copy()
fish_count = {n:fishes.count(n) for n in range(9)}

total_days = 256

for day in range(total_days):
    new_fish_count = {n-1:fish_count[n] for n in range(9)}
    new_fish_count[8] = new_fish_count[-1]
    new_fish_count[6] += new_fish_count[-1]
    new_fish_count.pop(-1)
    fish_count = new_fish_count
    
print(fish_count)
print(sum(fish_count.values()))

{0: 141609768142, 1: 168220217323, 2: 174580192795, 3: 192297609038, 4: 216599442496, 5: 220638749612, 6: 264026507130, 7: 118312776454, 8: 144241338605}
1640526601595


In [277]:
# day 7

with open('advent2021/day7.txt') as f:
    lines = f.readlines()
    
data = lines[0].strip().split(',')
data = list(map(int, data))

In [289]:
# part 1

median = np.median(data)
absolute_distance = list(map(lambda x:abs(x - median), data))

print(f'sum absolute_distance: {np.sum(absolute_distance)}')

sum absolute_distance: 325528.0


In [314]:
# part 2

def fuel_needed(dist):
    return sum(range(dist+1))

def total_fuel(alignment_point):
    fuel_list = list(map(lambda x:fuel_needed(abs(x - int(alignment_point))), data))
    return np.sum(fuel_list)
    

In [329]:
# part 2 - find the turning point in the function

left = 0
right = max(data) - 1

# for illustration purpose. not needed indeed
# left_direction = math.copysign(1, total_fuel(left + 1) - total_fuel(left))
# right_direction = math.copysign(1, total_fuel(right + 1) - total_fuel(right))

found = False

while not found:
    mid_point = int( (left + right) / 2)
    mid_direction = math.copysign(1, total_fuel(mid_point + 1) - total_fuel(mid_point))
    print(f'{left=}, {mid_point=}, {right=}')
    if mid_direction == -1:
        left = mid_point
    else:
        right = mid_point
        
    if right-left<3:
        found = True


print(f'left:{left=}:{total_fuel(left)=}')
print(f'left:{mid_point=}:{total_fuel(mid_point)=}')
print(f'right:{right=}:{total_fuel(right)=}')  # supposely, right is the turning point


left=0, mid_point=881, right=1762
left=0, mid_point=440, right=881
left=440, mid_point=660, right=881
left=440, mid_point=550, right=660
left=440, mid_point=495, right=550
left=440, mid_point=467, right=495
left=440, mid_point=453, right=467
left=453, mid_point=460, right=467
left=453, mid_point=456, right=460
left=456, mid_point=458, right=460
left:left=458:total_fuel(left)=85018811
left:mid_point=458:total_fuel(mid_point)=85018811
right:right=460:total_fuel(right)=85015836


In [330]:
# day 8

with open('advent2021/day8.txt') as f:
    lines = f.readlines()
    
data = [line.strip().split('|') for line in lines]
data = [(line[0].strip().split(' '), line[1].strip().split(' ')) for line in data]

In [348]:
# part 1

# 1: 2 segments
# 4: 4 segments
# 7: 3 segments
# 8: 7 segments

def count_1478(tokens):
    match = set([2, 4, 3, 7])
    l = map(len, tokens)
    l = map(lambda x: x in match, l)
    return sum(l)

l = [count_1478(line[1]) for line in data]
sum(l)

In [412]:
# part 2
data[0][0]

def decode(input_codes, output_codes):
    
    # a dict with the count of occurance of input segments
    merged_input = ''.join(input_codes)
    input_count = {i:merged_input.count(i) for i in 'abcdefg'}
    
    # deterministic mapping of code 1, 4, 7, 8
    code_1 = list(filter(lambda x:len(x)==2, input_codes))[0]
    code_4 = list(filter(lambda x:len(x)==4, input_codes))[0]
    code_7 = list(filter(lambda x:len(x)==3, input_codes))[0]
    code_8 = list(filter(lambda x:len(x)==7, input_codes))[0]
    
    # build the segments (dependency on sequence of processing)
    segment_A = list(set(code_7) - set(code_1))[0]
    segment_B = list(filter(lambda x:input_count[x]==6, input_count))[0]
    segment_E = list(filter(lambda x:input_count[x]==4, input_count))[0]
    segment_F = list(filter(lambda x:input_count[x]==9, input_count))[0]
    segment_C = list(set(code_7) - set(segment_A + segment_F))[0]
    segment_D = list(set(code_4) - set(segment_B + segment_C + segment_F))[0]
    segment_G = list(set(code_8) - set(segment_A + segment_B + segment_C + segment_D + segment_E + segment_F))[0]
#     print(f'{segment_A=}')    
#     print(f'{segment_B=}')
#     print(f'{segment_C=}')
#     print(f'{segment_D=}')
#     print(f'{segment_E=}')
#     print(f'{segment_F=}')
#     print(f'{segment_G=}')
    
    # build the code dict
    code_dict = {
        0: segment_A + segment_B + segment_C + segment_E + segment_F + segment_G,
        1: segment_C + segment_F,
        2: segment_A + segment_C + segment_D + segment_E + segment_G,
        3: segment_A + segment_C + segment_D + segment_F + segment_G,
        4: segment_B + segment_C + segment_D + segment_F,
        5: segment_A + segment_B + segment_D + segment_F + segment_G,
        6: segment_A + segment_B + segment_D + segment_E + segment_F + segment_G,
        7: segment_A + segment_C + segment_F,
        8: 'abcdefg',
        9: segment_A + segment_B + segment_C + segment_D + segment_F + segment_G
    }
    
    reverse_code_dict = {''.join(sorted(code_dict[k])):k for k in code_dict}
    
    output_list = [reverse_code_dict[''.join(sorted(code))] for code in output_codes]
    return int(''.join(map(str, output_list)))
    


In [416]:
l = [decode(line[0], line[1]) for line in data]
np.sum(l)

973499

In [428]:
# day 9

with open('advent2021/day9.txt') as f:
    lines = f.readlines()

temp = [line.strip() for line in lines]

data = []
for line in temp:
    data.append([int(c) for c in line])
    
arr = np.array(data)    

In [448]:
# part 1
def is_minima(i, j):
    l = arr[i-1, j] if i>0 else 10
    r = arr[i+1, j] if i<arr.shape[0]-1 else 10
    u = arr[i, j-1] if j>0 else 10
    d = arr[i, j+1] if j<arr.shape[1]-1 else 10
    v = arr[i, j]

    is_minima = (v<l) and (v<r) and (v<u) and (v<d)
    return is_minima
    
min_list = []
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if is_minima(i, j):
            min_list.append((i, j, arr[i,j] + 1))
            

np.sum([item[2] for item in min_list])

In [458]:
# part 2

# mask for area map
marked = (arr==9)*1

# use recursion to calculate area
def basin_area(i, j):
    area = 0
    
    # out of boundary
    if (i<0) or (j<0) or (i>marked.shape[0]-1) or (j>marked.shape[1]-1):
        return area
    
    
    # unmarked count the area
    if marked[i, j]==0:
        marked[i, j] = 1
        area +=1
        
        # explore the suroundings
        area += basin_area(i-1, j)
        area += basin_area(i+1, j)
        area += basin_area(i, j-1)
        area += basin_area(i, j+1)
    
    return area
    

    

In [459]:
basin_list = []
for item in min_list:
    i, j, _ = item
    basin_list.append((i, j, basin_area(i, j)))

sorted_basin_list = sorted(basin_list, key=lambda tup: tup[2])
np.product([item[2] for item in sorted_basin_list[-3:]])    

In [468]:
# day 10

with open('advent2021/day10.txt') as f:
    lines = f.readlines()

lines = [line.strip() for line in lines]

In [470]:
lines[0]

'({{[<{[{[[<([[<><>][{}()]]<([]{})[<>()]>)><<<([]())>>{([()<>][{}{}])<[<>()]{()()}>}>]<(<[[[]<>]({}{})]{{{}<>}'

In [490]:
error_points = {
    ')': 3,
    ']': 57,
    '}': 1197,
    '>': 25137    
}

matched_token = {
    '(': ')',
    '[': ']',
    '{': '}',
    '<': '>'
}

def syntax_check(line_input):
    syntax_stack = []
    for c in line_input:
        if c in '({[<':
            syntax_stack.append(c)
        elif c in ')}]>':
            if len(syntax_stack)==0:
                return -1
            expected_token = matched_token[syntax_stack.pop()]
            if (c!=expected_token):
                return error_points[c]
    return 0





In [491]:
syntax_checked_lines = [syntax_check(line) for line in lines]
np.sum(syntax_checked_lines)

In [499]:
incomplete_lines = []

for i in range(len(lines)):
    if syntax_checked_lines[i]==0:
        incomplete_lines.append(lines[i])


In [523]:
autocomplete_score = {
    '(': 1,
    '[': 2,
    '{': 3,
    '<': 4
}
    
def autocomplete_check(line_input):
    syntax_stack = []
    for c in line_input:
        if c in '({[<':
            syntax_stack.append(c)
        elif c in ')}]>':
            if len(syntax_stack)==0:
                return -1
            expected_token = matched_token[syntax_stack.pop()]
            if (c!=expected_token):
                return error_points[c]
    
    # scoring
    score = 0
    while (len(syntax_stack)>0):
        score = score*5 + autocomplete_score[syntax_stack.pop()]
    return score





In [524]:
l = [autocomplete_check(line) for line in incomplete_lines]

In [526]:
sorted(l)[int(len(l)/2)]

2429644557